dbtlearn:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: airbnb
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: transform
      schema: "{{ env_var('TARGET_SCHEMA') }}"
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
