# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    environment: dbt-env

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ SNOWFLAKE_ACCOUNT }}
      DBT_TARGET: ${{ DBT_TARGET }}
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install dbt
        run: pip install dbt-snowflake==1.2.0
      
      - name: debug env vars
        run: echo "$SNOWFLAKE_ACCOUNT" "$DBT_TARGET"
        
      - name: dbt smoke test
        run: dbt --profiles-dir=cicd debug

      - name: Install dbt packages
        run: dbt  --profiles-dir=cicd deps
      
      - name: Clean Up Test schema
        run: echo "TODO"
      
      - name: Run dbt
        run: dbt --profiles-dir=cicd run

      - name: Run snapshots
        run: dbt --profiles-dir=cicd snapshot
        
      - name: Run tests
        run: dbt --profiles-dir=cicd test        
        
